### ISSUE TITLE
Account page feedback doesn't tell you what to do

### ISSUE THREAD

**Issue by saschwarz** [epicweb-dev/epicshop#209]
![Screenshot 2024-07-13 at 6 32 40 PM](https://github.com/user-attachments/assets/2699c871-fcc8-4fb2-973d-bec493bf74b4)

I can't tell from reading these messages whether I'm correctly or incorrectly configured.
It seems to imply that the app is using the wrong discord account(?) but I couldn't find where that is configured.
It would be helpful to have concrete steps to follow to resolve this problem - if there is a problem.

Also what does "Opt out of presence" mean? I'm guessing it's a discord feature? It would be helpful to describe why you would/wouldn't want to do that.

Lastly, it would be helpful if links that take the user away from the app opened in a new tab and/or had an icon indicating the links aren't within the app itself.

**Comment by kentcdodds** [comment]
I've improved the account page a bit. To answer your questions directly:

> It seems to imply that the app is using the wrong discord account(?) but I couldn't find where that is configured.

I'm not certain why you're thinking you're connected to the wrong discord account. That looks ok based on your screenshot.

> Also what does "Opt out of presence" mean?

This is regarding the presence feature in the navigation:

<img width="424" alt="image" src="https://github.com/user-attachments/assets/68b243d6-08d2-45cc-bf13-ccf49b01779c">

Clicking opt out will remove you from that list.

> links that take the user away from the app opened in a new tab

The Discord connection link actually works best by you not opening into a new tab because the flow brings you back to the app. Are there other links you'd like to have indications on?

**Comment by saschwarz** [comment]
> > It seems to imply that the app is using the wrong discord account(?) but I couldn't find where that is configured.
> 
> I'm not certain why you're thinking you're connected to the wrong discord account. That looks ok based on your screenshot.

@kentcdodds  My point was it isn't clear to someone who didn't code the page that it is OK. The first sentence shows you are logged in with one account (on your device) and the second sentence implies you are logged in as a different one (to discord). 

Their proximity implies that they are related. If they really aren't related putting an <hr/>  or section names: General and Discord between them would have clarified things.

Because they are below one another, to my thinking I was in an error situation because they aren't both showing the same string in the parens.

> > links that take the user away from the app opened in a new tab
> 
> The Discord connection link actually works best by you not opening into a new tab because the flow brings you back to the app. Are there other links you'd like to have indications on?

The onboarding and support links (among others in the app) load in the same tab which isn't helpful. So to have those have an external link icon would be helpful.
