### ISSUE TITLE
(destructured parameter) is undefined

### ISSUE THREAD

**Issue by RobbertWolfs** [epicweb-dev/epicshop#215]
Clicking the "Files" button results in the following error:

![image](https://github.com/user-attachments/assets/40f35c50-b635-48f3-9247-78442a974d4d)

![image](https://github.com/user-attachments/assets/484b5cd1-38f4-4d66-9835-fe68fdb9d80e)

![image](https://github.com/user-attachments/assets/2f802c7f-16ac-4caa-bc2b-7580857ccb29)

**Comment by kentcdodds** [comment]
Fixed in https://github.com/epicweb-dev/epicshop/commit/e13eed56a8d1ebf9bdab02b7be10b47917cab738 (forgot to mention this issue in the commit).

Thanks for reporting!

This is the reason it's best to not use `useLoaderData` outside the route that has the loader in it. Too easy to miss something in a refactor 😅

**Comment by RobbertWolfs** [comment]
Thanks for the quick fix 🚀
